# Makefile for Wii-specific code

CXXFLAGS	+= -DWII -DHW_RVL -DUSE_EXPANSION -D__wii__

LDFLAGS		+= -mrvl

LIBPATHS 	+= -L$(DEVKITPRO)/libogc2/lib/wii

OBJ		+= \
		gc_memory/TLB-Cache-hash.o \
		vm/dsihandler.o \
		vm/wii_vm.o \
		main/wii.o

OBJ_INPUT	+= \
		gc_input/controller-Classic.o \
		gc_input/controller-WiimoteNunchuk.o

LIB		+= -lwiiuse -lbte -lz

