# Makefile for Wii-specific code

CXXFLAGS	+= -DWII -DHW_RVL -DUSE_EXPANSION -D__wii__

LDFLAGS		+= -mrvl

LIBPATHS 	+= -L$(DEVKITPRO)/libogc2/wii/lib
INCLUDE 	+= -I$(DEVKITPRO)/libogc2/wii/include

OBJ		+= \
		vm/dsihandler.o \
		vm/wii_vm.o \
		main/wii.o \
		main/Autoboot.o

OBJ_INPUT	+= \
		gc_input/controller-Classic.o \
		gc_input/controller-WiimoteNunchuk.o

LIB		+= -lwiiuse -lbte -lz

