# Makefile MUPEN64 for glN64 + MenuV2 + GC 

ELF		= cube64-glN64.elf
DOL		= cube64-glN64.dol

CFLAGS		= -DHW_DOL -DUSE_TLB_CACHE -DGLN64_GX -DTINY_TLBCACHE

LDFLAGS		= -mogc

LIBPATHS	= -L$(DEVKITPRO)/libogc/lib/cube -L$(DEVKITPRO)/libfat/libogc/lib/cube

OBJ		= \
		main/ROM-Cache.o \
		gc_memory/ARAM.o \
		gc_memory/TLB-Cache.o \

include Makefile.menu2

