#Makefile MUPEN64 for glN64_GX + MenuV2 + GC + Expansion Pak

ELF		= cube64-glN64-exp.elf
DOL		= cube64-glN64-exp.dol

CXXFLAGS	+= -DUSE_EXPANSION -DGC_BASIC -DLAZY_GEN_CALLS

include Makefile.glN64
include Makefile.gc
include Makefile.base

