#Makefile MUPEN64 for Rice + MenuV2 + GC

ELF		= cube64-Rice.elf
DOL		= cube64-Rice.dol

CFLAGS		= -DHW_DOL -DUSE_TLB_CACHE -DARAM_BLOCKCACHE -DTINY_TLBCACHE

LDFLAGS		= -mogc

LIBPATHS	= -L$(DEVKITPRO)/libogc/lib/cube -L$(DEVKITPRO)/libfat/libogc/lib/cube

OBJ		= \
		main/ROM-Cache.o \
		gc_memory/ARAM.o \
		gc_memory/TLB-Cache.o \

include Makefile.Rice

