#Makefile MUPEN64 for Rice + MenuV2 + Wii 

ELF		= wii64-Rice.elf
DOL		= wii64-Rice.dol

#CFLAGS		= 
INCLUDE 	=
#LD			= 
#LDFLAGS 	=
#LIBPATHS	= 
LIB			= 

include Makefile.Rice
include Makefile.wii
include Makefile.base

