#Makefile MUPEN64 for Rice + MenuV2 + GC

ELF		= cube64-Rice.elf
DOL		= cube64-Rice.dol

#CFLAGS		=
INCLUDE 	=
#LD			= 
#LDFLAGS 	=
#LIBPATHS	= 
LIB			= 

include Makefile.Rice
include Makefile.gc
include Makefile.base

