#Makefile MUPEN64 for Rice + MenuV2 + GC + Expansion Pak

ELF		= cube64-Rice-exp.elf
DOL		= cube64-Rice-exp.dol

CXXFLAGS	+= -DUSE_EXPANSION
INCLUDE 	=
LIB			= 

include Makefile.Rice
include Makefile.gc
include Makefile.base

