# Makefile for Wii-specific code

CXXFLAGS	+= -DWII -DHW_RVL -DUSE_EXPANSION -DMEM2XFB -DUSE_INLINE_STORES -D__wii__

LDFLAGS		+= -mrvl

LIBPATHS 	+= -L$(DEVKITPRO)/libogc/lib/wii -L$(DEVKITPRO)/libfat/libogc/lib/wii

OBJ		+= \
		gc_memory/TLB-Cache-hash.o \
		vm/dsihandler.o \
		vm/wii_vm.o

OBJ_INPUT	+= \
		gc_input/controller-Classic.o \
		gc_input/controller-WiimoteNunchuk.o

LIB		+= -lwiiuse -lbte -lz

